### ISSUE TITLE
It doesn't convert notes...

### ISSUE THREAD

**Issue by CloverFeywilde** [tenphi/sm-parser#2]
It's a crying shame. I was so hopeful that this could be a good solution for me, but the real meat of it's usefulness is lost, as it doesn't convert the notes section. 

Is there perhaps something I'm missing or any way we can get this functionality added? I'm developing a game that could seriously use this. I can help however I can.

**Comment by tenphi** [comment]
It’s a really simple version of sm parser. If you open that little source file you will see that it does parse notes. But it supports only simple sm files. It was a while since I wrote it. So I can’t remember any condition for successful parsing.

You can try to write your own parser if you wish. It’s not so hard.
